require File.dirname(__FILE__) + "/chemcaster/service"
require File.dirname(__FILE__) + '/chemcaster/service'
require File.dirname(__FILE__) + '/chemcaster/registry'
require File.dirname(__FILE__) + '/chemcaster/structure'
require File.dirname(__FILE__) + '/chemcaster/query'
require File.dirname(__FILE__) + '/chemcaster/image'
require File.dirname(__FILE__) + '/chemcaster/link'
require File.dirname(__FILE__) + '/chemcaster/index'
require File.dirname(__FILE__) + '/chemcaster/item'
require File.dirname(__FILE__) + '/chemcaster/representation'
require File.dirname(__FILE__) + '/chemcaster/media_type'
require File.dirname(__FILE__) + '/chemcaster/error'

require 'rubygems'
require 'json'